### ISSUE TITLE
Potential EN Corrections

### ISSUE THREAD

**Issue by alexckuhn** [linguacamp/2015-Berlin#1]
Below are minor corrections I made to the EventBright text in English. You use the initial description of LinguaCamp also on the main website, so you could update it in both areas:

---

EN: LinguaCamp - the unconference
There is no audience, only participants.
Meet people from abroad, teach your language, learn their language, try out new methods and technologies, exchange knowledge, design new teaching material, build intercultural understanding and teaching skills, and share your work.

All levels, all languages, all ages are welcome!

The conference will be held in German, English, and French (and maybe even your language)!

More on :
    • http://linguacamp.com
    • http://linguacamp.org
    • http://linguacamp.net
    • https://twitter.com/linguacamps
    • http://scoop.it/linguacamp
    • http://facebook.com/linguacamps

This is a two-day event. You can sign up for Saturday and/or Sunday. Please sign up only if you are sure you can attend.

Happy LinguaCamping!

**Comment by chrisreuter** [comment]
Vielen Dank Alex!
