### ISSUE TITLE
DE: Eventbrite registration shows "tickets no longer available" message

### ISSUE THREAD

**Issue by linguacamp** [linguacamp/2015-Berlin#2]
At least for Saturday October 3 where there are already 50 sign-ups and "100 tickets" still available shown on the frontpage.
http://www.eventbrite.de/e/linguacamp-berlin-2015-registration-18347584118
Sunday seams to work. At least when you jump directly on Sunday.

![eventbrite-linguacamp register 2015-09-24](https://cloud.githubusercontent.com/assets/5417680/10122248/a5e517b8-6512-11e5-8b59-bd57aea19055.png)

**Comment by chrisreuter** [comment]
Called hotline Friday September 25. They confirmed the bug couldn't solve the problem. Ask to wait until Monday so that a programmer could have a look at it.

**Comment by chrisreuter** [comment]
Replaced our event link http://linguacamp2015.eventbrite.de on all our relevant webpages by http://linguacamp.com and set up an easy sign up procedure by email there.

Since than we got 7 sign-ups (= 5 for Sat + 2 for Sun) via email.

**Comment by chrisreuter** [comment]
Today rechecked. Can't reproduce the bug on http://linguacamp2015.eventbrite.de
Can anyone double check?

**Comment by linguacamp** [comment]
DE: Einschreibung auf Eventbrite scheint wieder zu funktionieren.
